### ISSUE TITLE
appMetrics 2.0.0 indicator protocol document example appear not to accept "-"

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-metrics#138]
in the custom metrics documentation here: https://docs.pivotal.io/app-metrics/2-0/using.html#custom-metrics

it uses this example document:

```yml
---
apiVersion: indicatorprotocol.io/v1
kind: IndicatorDocument

metadata:
  labels:
    deployment: "my deployment name"

spec:
  product:
    name: org,space,app-name
    version: 0.0.1

  indicators:
    - name: "Custom 500 Error Indicator"
      promql: "sum(avg_over_time(customMetricName500{source_id=\"$sourceId\"}[1m]))"
      documentation:
        title: "Custom Metric 500 Errors
      presentation:
        units: "none"
```

however when you try to apply this document, it claims that the "spec.indicators[0].name" has an invalid name regex:

```json
>{"error":"Invalid request","exception":"spec.indicators[0].name must match \"[a-zA-Z_:][a-zA-Z0-9_:]*\""}%
```

it appears that `spec.indicators[0].name` is much happier without dashes in it, or with underscores:

```
- name: custom500errorindicator 
# or
- name: custom_500_error_indicator
```

this will upload just fine.

just giving a heads up 👍 thanks!
